### ISSUE TITLE
Fill out license template

### ISSUE THREAD

**Issue by MEGASTACK** [CMPUT301F15T03/301p#16]
Once we have a theme/name, the license template should be filled out appropriately.

**Comment by rosshamish** [comment]
For reference, I think John means these lines in LICENSE

https://github.com/CMPUT301F15T03/301p/blob/master/LICENSE#L634
```
{one line to give the program's name and a brief idea of what it does.}
    Copyright (C) {year}  {name of author}
```

https://github.com/CMPUT301F15T03/301p/blob/master/LICENSE#L655
`{project}  Copyright (C) {year}  {fullname}`

**Comment by MEGASTACK** [comment]
More acurately, just somewhere have a copypastable, pre-set-up, consistent block of this such that it can be copypasta'd into each file where it belongs
