### ISSUE TITLE
US01.01.01 - As an owner, I want to remove, edit, or add an item to my inventory that I want to share. It will have a name, quantity, quality, category, if I want to share it with others, and comments.

### ISSUE THREAD

**Issue by kyleoshaughnessy** [CMPUT301F15T03/301p#18]

**Comment by udeyrishi** [comment]
See [use cases](https://github.com/CMPUT301F15T03/301p/wiki/1.1-Use-Cases-%5BInventory%5D)

**Comment by mabuyo** [comment]
Most of this was addressed in P4 milestone, except for comments. We haven't discussed comments yet so may move the comments aspect of this issue to P5 milestone.

**Comment by quentinlautischer** [comment]
Comments may be interpreted as item description? Anyone else think so?

**Comment by kyleoshaughnessy** [comment]
Ya, I think so. There is no spec for other users to comment that I know of. So a description may just be a big text are for comments.

**Comment by kyleoshaughnessy** [comment]
I think this is done. We all agree this is a description of the item.

**Comment by rosshamish** [comment]
@CMPUT301F15T03/owners I agree with @kyleoshaughnessy, I think comments is a description of the item, and that this can be closed.
