### ISSUE TITLE
US01.07.01 - As an owner, I want the category for an item to be one of 10 relevant categories of books.

### ISSUE THREAD

**Issue by kyleoshaughnessy** [CMPUT301F15T03/301p#24]

**Comment by udeyrishi** [comment]
See [use cases](https://github.com/CMPUT301F15T03/301p/wiki/1.1-Use-Cases-%5BInventory%5D) 1.01.01 and 1.02.01

**Comment by mabuyo** [comment]
Our categories are of photography equipment! Not books, as this user story in the Project Description suggests.
