### ISSUE TITLE
US01.08.01 - As an owner, I want the entry of an item to have minimal required navigation in the user interface. It must be easy to describe an item.

### ISSUE THREAD

**Issue by kyleoshaughnessy** [CMPUT301F15T03/301p#25]

**Comment by udeyrishi** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.1-Use-Cases-%5BInventory%5D) 01.01.01

**Comment by mabuyo** [comment]
Done and tested. Navigate to Inventory -> Add Item FAB, nice and simple.
