### ISSUE TITLE
US06.01.01 - As an owner, I want to optionally attach photographs of items to the item. Photos are optional for items.

### ISSUE THREAD

**Issue by quentinlautischer** [CMPUT301F15T03/301p#30]

**Comment by mabuyo** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.6-Use-Cases-%5BPhotographs-of-Items%5D) 06.01.01

**Comment by kyleoshaughnessy** [comment]
Photos are now added to the item at add time or edit time, and are currently viewable by the primary user. These will be viewable in the inspect item view soon. Testing has not been done yet.

**Comment by kyleoshaughnessy** [comment]
Tested in PhotoUITest.java

**Comment by kyleoshaughnessy** [comment]
+Uml updated
+Javadocs completed
