### ISSUE TITLE
US06.02.01 - As an owner, I want to view any attached photograph for an item.

### ISSUE THREAD

**Issue by quentinlautischer** [CMPUT301F15T03/301p#31]

**Comment by udeyrishi** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.6-Use-Cases-%5BPhotographs-of-Items%5D) 06.02.01

**Comment by kyleoshaughnessy** [comment]
You can view the attached photos of your items, this needs to be added to items in insect item view. testing not started.

**Comment by kyleoshaughnessy** [comment]
Tested in PhotoUITest.java

**Comment by kyleoshaughnessy** [comment]
+Uml updated
+Javadocs completed
