### ISSUE TITLE
US10.01.01 - As a user, I should be able to specify if I download images or not.

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#33]

**Comment by udeyrishi** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.10-Use-Cases-%5BUser%5D) 10.01.01

**Comment by kyleoshaughnessy** [comment]
-Feature has been implemented
-UI test cases have been implemented and are passing
-UML diagrams have been updated with current class definitions
