### ISSUE TITLE
US06.03.01 - As an owner, I want to delete any attached photograph receipt on an item, so that unclear images can be re-taken.

### ISSUE THREAD

**Issue by quentinlautischer** [CMPUT301F15T03/301p#34]

**Comment by mabuyo** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.6-Use-Cases-%5BPhotographs-of-Items%5D) 06.03.01

**Comment by kyleoshaughnessy** [comment]
The owner can now delete items in the add or edit item views. Testing not yet started.

**Comment by kyleoshaughnessy** [comment]
Test in PhotoUITest.java

**Comment by kyleoshaughnessy** [comment]
+Uml updated
+Javadocs completed
