### ISSUE TITLE
US06.04.01 - As a sysadmin, I want each receipt image file to be under 65536 bytes in size.

### ISSUE THREAD

**Issue by quentinlautischer** [CMPUT301F15T03/301p#38]

**Comment by mabuyo** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.6-Use-Cases-%5BPhotographs-of-Items%5D) 06.01.01

**Comment by kyleoshaughnessy** [comment]
Photos are all under 64k, This needs to be tested.

**Comment by kyleoshaughnessy** [comment]
Tested in PhotoUITest.java

**Comment by kyleoshaughnessy** [comment]
+Uml updated
+Javadocs completed
