### ISSUE TITLE
US06.05.01 - As a borrower, if photo downloads are disabled, I want the option of manually choosing inventory photos to download.

### ISSUE THREAD

**Issue by quentinlautischer** [CMPUT301F15T03/301p#40]

**Comment by udeyrishi** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.6-Use-Cases-%5BPhotographs-of-Items%5D) 06.05.01

**Comment by kyleoshaughnessy** [comment]
NOTE: for this functionality, instantiate a Configuration object, say, configuration, and check the value of configuration.isDownloadImagesEnabled() to determine if manual photo downloading options should be shown.

**Comment by MEGASTACK** [comment]
This one is looking pretty good.

**Comment by kyleoshaughnessy** [comment]
Tested in PhotoUITest.java
