### ISSUE TITLE
US03.02.01  As an owner, any of my publicly shared items will be browseable / searchable by my friends.

### ISSUE THREAD

**Issue by rosshamish** [CMPUT301F15T03/301p#43]

**Comment by udeyrishi** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.3-Use-Cases-%5BBrowsing%5D) 1.3.2.1

**Comment by kyleoshaughnessy** [comment]
Very similar to us01.04.01, we could knock out two stories with one stone.

**Comment by quentinlautischer** [comment]
Done
