### ISSUE TITLE
US04.01.01 - As a borrower, I want to offer a trade with a friend. A trade will consist of an item from the owner's inventory and 0 or more items from the borrower's inventory.

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#44]

**Comment by mabuyo** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.4-Use-Cases-%5BTrading%5D) 1.4.1

**Comment by rosshamish** [comment]
Closing as part of Part 4, as PR #64 passes test TradeUITest.testOfferTradeWithFriends, and "0 or more items" functionality will come as part of #48 Editing a trade while composing.
