### ISSUE TITLE
US04.02.01 - As an owner, when a borrower offers a trade I will be notified of the trade.

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#45]

**Comment by mabuyo** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.4-Use-Cases-%5BTrading%5D) 1.4.2

**Comment by rosshamish** [comment]
If by notify, we mean that it will show up in your Trades list the next time you refresh it, then this is done.
@CMPUT301F15T03/owners thoughts? I guess since we don't have an actual "notifications" queue or mechanism.

**Comment by kyleoshaughnessy** [comment]
Good point, past years videos showed a notification style system being used. Would it be to much work to implement that at this stage? perhaps it will be.

**Comment by udeyrishi** [comment]
Notifications shouldn't be too hard to implement. We can have a config setting for this

**Comment by kyleoshaughnessy** [comment]
I think we would need to poll every so often on some network thread to get this figured out. Could be non-trivial.

**Comment by udeyrishi** [comment]
Never mind. It could be. We will need a server to push the notifications. Let's just do email then

**Comment by udeyrishi** [comment]
Or polling, as you suggested
