### ISSUE TITLE
US04.04.01 - As an owner, upon declining a trade I can offer a counter trade initialized with the items of the declined trade.

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#47]

**Comment by rosshamish** [comment]
Question:

In #44 , it is implied that the borrower asks for **one** item and offers **zero or more** items in return. Can the owner send a counter-offer with **multiple items** (not just the one) in return for the borrower's zero or more?

**Comment by mabuyo** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.4-Use-Cases-%5BTrading%5D) 1.4.4
