### ISSUE TITLE
US04.05.01 - As a borrower or owner, when composing a trade or counter-trade I can edit the trade.

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#48]

**Comment by mabuyo** [comment]
See [use case](https://github.com/CMPUT301F15T03/301p/wiki/1.4-Use-Cases-%5BTrading%5D) 1.4.5.1

**Comment by rosshamish** [comment]
In-progress. Adding items to the trade is ongoing.
