### ISSUE TITLE
US04.06.01 - As a borrower, when composing a trade or counter-trade I can delete the trade

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#49]

**Comment by mabuyo** [comment]
See [use case] (https://github.com/CMPUT301F15T03/301p/wiki/1.4-Use-Cases-%5BTrading%5D) 1.4.6.1, 1.4.6.2

**Comment by rosshamish** [comment]
This is done! It can be deleted by either cancelling the trade via the Cancel button, or merely by navigating away from the activity (back button, kill the app, anything)
