### ISSUE TITLE
US04.09.01 - As an owner or borrower, I can browse all past and current trades involving me as either borrower or owner. I should be able to look at my trades and trades offered to me.

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#52]

**Comment by rosshamish** [comment]
Duplicate of #51 "As an owner or borrower, I can browse all past and current trades involving me." ?

**Comment by mabuyo** [comment]
See [use case] (https://github.com/CMPUT301F15T03/301p/wiki/1.4-Use-Cases-%5BTrading%5D) 1.4.8

**Comment by rosshamish** [comment]
This is done!
