### ISSUE TITLE
Editing an item results in a new item being created

### ISSUE THREAD

**Issue by MEGASTACK** [CMPUT301F15T03/301p#56]
#22

**Comment by mabuyo** [comment]
This is because at the time I was working on it we were still talking about implementing UUID's to grab the right item from inventory and update it. @kyleoshaughnessy are you working on this right now or I can pick it up where I left off?

**Comment by kyleoshaughnessy** [comment]
I was working on that, yes, its partially implemented. the idea is that Inventory.items is now a Map<UUID, Item>. I was trying to fix the existing code that treats this as an ArrayList<Items>. Im currently in a lab until 5... i could check into a different branch and someone can take over.

**Comment by kyleoshaughnessy** [comment]
Fixed!!!

**Comment by kyleoshaughnessy** [comment]
Someone can confirm and close this issue, To confirm, uninstall your application and make a new user!

**Comment by MEGASTACK** [comment]
COOOOOL :shipit:
