### ISSUE TITLE
testViewOwnInventory throws an IllegalStateException when all the tests are run

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#66]
The test works when it's run individually, but fails when all the tests are run. I'm guessing some timing issues/race conditions.
<img width="1201" alt="screen shot 2015-11-12 at 7 38 07 pm" src="https://cloud.githubusercontent.com/assets/4692593/11137549/f16de91c-8975-11e5-9e64-247158cb2a24.png">

**Comment by MEGASTACK** [comment]
This might be an observer pattern issue... I may have fixed it independently
