### ISSUE TITLE
Cached (Local?) DataManager fails to deserialize json (gson exception)

### ISSUE THREAD

**Issue by MEGASTACK** [CMPUT301F15T03/301p#68]
Steps to repro:
- Add yourself as a friend
- Add an item to your inventory
- From "BrowseableInventories" (Browse) page, initiate a trade with yourself
- Go offline
- Navigate to Trades
- BOOM!

I need to verify that this still happens when you propose trade with someone else

This happens with CDM, QDM
This happens when you add yourself OR add a different friend... doesnt matter.

**Comment by MEGASTACK** [comment]
I think this is fixed now.

**Comment by udeyrishi** [comment]
@MEGASTACK Can you please verify if it's done?

**Comment by kyleoshaughnessy** [comment]
its fixed
